import { useState } from "react";

import api from "./api";

export default function Upload({
  refreshClaims
}) {

  const [file, setFile] = useState(null);

  const [loading, setLoading] =
    useState(false);

  const [result, setResult] =
    useState(null);

  /* ================= DOWNLOAD REPORT ================= */

  const downloadReport = () => {

    if (!result) return;

    const report = `
==============================
 AI INSURANCE CLAIM REPORT
==============================

Policy Number:
${result.analysis?.extracted_fields?.policyNumber || "N/A"}

Hospital:
${result.hospital_name || "N/A"}

Claim Amount:
${result.claim_amount || "N/A"}

Risk Score:
${result.risk_score || 0}

Risk Level:
${result.risk_level || "Low"}

Fraud Detection:
${result.analysis?.fraud_flag ? "YES" : "NO"}

Justification:
${result.justification || "N/A"}

Missing Fields:
${
  result.analysis?.missing_fields?.length > 0
    ? result.analysis.missing_fields.join(", ")
    : "None"
}

==============================
Generated by AI Claim Analyzer
==============================
`;

    const blob = new Blob(
      [report],
      { type: "text/plain" }
    );

    const url =
      window.URL.createObjectURL(blob);

    const a =
      document.createElement("a");

    a.href = url;

    a.download =
      "claim_report.txt";

    a.click();

    window.URL.revokeObjectURL(url);
  };

  /* ================= FILE UPLOAD ================= */

  const uploadFile = async () => {

    try {

      if (!file) {

        alert("Please select a file");

        return;
      }

      setLoading(true);

      const formData = new FormData();

      formData.append("file", file);

      const res = await api.post(
        "/upload",
        formData
      );

      setResult(res.data.claim);

      refreshClaims();

    } catch (err) {

      console.error(err);

      alert("Upload failed");

    } finally {

      setLoading(false);
    }
  };

  return (

    <div>

      <input
        type="file"
        onChange={(e) =>
          setFile(e.target.files[0])
        }
      />

      <br />
      <br />

      <button
        className="upload-btn"
        onClick={uploadFile}
        disabled={loading}
      >

        {
          loading
            ? "Analyzing..."
            : "Upload & Analyze"
        }

      </button>

      {/* ================= LOADING ================= */}

      {
        loading && (

          <div
            style={{
              marginTop: "25px",
              textAlign: "center"
            }}
          >

            <div
              style={{
                width: "50px",
                height: "50px",
                border: "5px solid #1e293b",
                borderTop:
                  "5px solid #38bdf8",
                borderRadius: "50%",
                margin: "auto",
                animation:
                  "spin 1s linear infinite"
              }}
            />

            <p
              style={{
                marginTop: "15px",
                color: "#38bdf8",
                fontWeight: "bold"
              }}
            >
              AI is analyzing claim document...
            </p>

          </div>
        )
      }

      {/* ================= RESULT ================= */}

      {

        result && !loading && (

          <div className="result-card">

            <h3>
              Analysis Result
            </h3>

            <p>
              <strong>Policy number:</strong>{" "}
              {
                result.analysis
                  ?.extracted_fields
                  ?.policyNumber
              }
            </p>

            <p>
              <strong>Hospital:</strong>{" "}
              {result.hospital_name}
            </p>

            <p>
              <strong>Claim Amount:</strong>{" "}
              {result.claim_amount}
            </p>

            <p>
              <strong>Risk Score:</strong>{" "}
              {result.risk_score}
            </p>

            <p>
              <strong>Risk Level:</strong>{" "}
              {result.risk_level}
            </p>

            <p>
              <strong>Fraud:</strong>{" "}
              {
                result.analysis?.fraud_flag
                  ? "Yes 🚨"
                  : "No ✅"
              }
            </p>

            <p>
              <strong>Justification:</strong>{" "}
              {result.justification}
            </p>

            <p>
              <strong>Missing Fields:</strong>{" "}

              {
                result.analysis
                  ?.missing_fields
                  ?.length > 0
                  ? result.analysis
                      .missing_fields
                      .join(", ")
                  : "None"
              }

            </p>

            <br />

            <button
              onClick={downloadReport}
              style={{
                marginTop: "15px",
                background: "#22c55e",
                color: "white",
                border: "none",
                padding: "10px 15px",
                borderRadius: "6px",
                cursor: "pointer",
                fontWeight: "bold"
              }}
            >
              Download Report
            </button>

          </div>
        )
      }

      {/* ================= SPINNER CSS ================= */}

      <style>
        {`
          @keyframes spin {

            0% {
              transform: rotate(0deg);
            }

            100% {
              transform: rotate(360deg);
            }
          }
        `}
      </style>

    </div>
  );
}